### ISSUE TITLE
Versioning of Ractive Documentation on Site

### ISSUE THREAD

**Issue by hbergren** [ractivejs/ractivejs.github.io#54]
Previously, there was a dropdown menu to select your Ractive version for documentation purposes. On the new website, that appears to be gone. I am working on a project that uses Ractive 0.4.0, and while we are planning on upgrading, it is useful to have the website provide that documentation in the meantime.

Any chance this can be brought back?

**Comment by fskreuz** [comment]
The legacy docs can be found at https://github.com/ractivejs/ractivejs.github.io/tree/dev/legacy

At the moment, the static site generator we use has no concept of versioning whatsoever. The old docs site was also written in a way that one API thingy was its own page so it's kinda unwieldy and needs cleanup. We're still looking into how to display the old docs correctly with the new setup. Stay tuned. 😄

**Comment by clarkd** [comment]
Would be good to have the old docs back - we're building on 0.7/0.8 and won't be able to upgrade just yet.

**Comment by fskreuz** [comment]
Yep. Still thinking of a good way to do it.

Most out-of-the-box static site generators don't do versioning. They're literally for static site/blog site generation, and not documentation. Most library docs that do have versioning are often custom-built, which I avoided because having something custom means if the maintainer who built it leaves and it breaks, you end up doing fixes than writing docs.

I once proposed [ReadTheDocs](https://github.com/ractivejs/ractive/pull/2747) specifically because it was for documentation and does versioning, but no one opted in because it was too docs-like and theming was not an option there.

And even if we could do versioning somehow, the old docs is a mashup of markdown, handlebars and a bunch of custom helper functions. Each function is also its own page, not like the current one which groups stuff by page. There's also 6 versions to clean up. Not impossible but will take a lot of time.

If anyone could step up and at least clean up those files in the legacy directory, even if it means only removing the handlebars bits from it and/or grouping functions and props into pages similar to the new docs, that would be great! 😄

**Comment by clarkd** [comment]
We use a platform called [Docbase](https://github.com/appbaseio/Docbase) for our customer-facing KB, it supports version OOB so might be worth taking a look. It was a little tricky to configure and there isn't much documentation (or at least there wasn't at the time) but might be worth taking a look.

**Comment by evs-chris** [comment]
Maybe we could use a simpler static site generator to pop out legacy docs mounted under ractive.js.org? Would still need to clean up all of the handlebars and other weird stuff in the legacy markdown, but we can probably just do 0.7 to begin with.

**Comment by fskreuz** [comment]
Was thinking of just concatenating older docs into one md file per version and sticking them in the current docs under some Legacy dropdown. For the most part, only the APIs and a few concept pages need preserving.

**Comment by lnryan** [comment]
So here's the thing: transitioning from 0.7 to 0.8 or 0.9 is non-trivial. It's not an inconvenience not to have access to these, it's actively causing problems....just for the sake of a shiny new layout? really not cool. I started using ractive because it was reliable and transparent. These kind of changes show a lack of awareness of the impact these decision have on those who are actually using the library.

I hear where you're coming from with the unwieldiness, but perhaps consider _finding a solution to it_ and _then_ switching over.

Incidentally - https://github.com/ractivejs/ractivejs.github.io/tree/dev/legacy goes NOWHERE. 

There have actually been several occasions where differences between the versioned pages allowed me to isolate issues.

**Comment by fskreuz** [comment]
>  I tried when 0.8 came out and it broke too many things.

[The next version after 0.9 is 1.0](https://github.com/ractivejs/ractive/issues/2949). Hopefully the API stabilizes in 0.9 before declaring stable. Your feedback during this stage is highly appreciated. 😄 

> I'm basically stuck on 0.7 with no upgrade path but a complete redesign, which is not feasible.

Migration from 0.7 to 0.8 and from 0.8 to 0.9 is documented in the [Migrating](https://ractive.js.org/get-started/migrating/) section.

> It's not an inconvenience not to have access to these, it's actively causing problems....just for the sake of a shiny new layout?

There have been several discussions already about overhauling the docs, and several site generators have been tested.

- https://github.com/ractivejs/ractive/issues/2857
- https://github.com/ractivejs/ractive/pull/2747
- https://github.com/ractivejs/ractive/issues/2271#issuecomment-160825524

In summary:

- Assemble - The old setup. Maintaining a custom build is annoying.
- Custom build - What Inferno does. Ractive can SSR. Same story with Assemble.
- GitBook - What Redux uses. No versioning. Treats `{{ }}` as template interpolators.
- Hexo - What Vuejs uses. Setup is annoying, not something contributors would like.
- Jekyll - What GitHub uses. Requires Ruby. Learning curve too far from usual site generators.
- Read the Docs - Has branch versioning, doesn't have theming options when using md.

The primary motive for using MkDocs was because it used vanilla markdown. You do not have to have a fully working local setup of the docs to contribute content to the docs, unless you're theming or writing inline demos.

> Incidentally - https://github.com/ractivejs/ractivejs.github.io/tree/dev/legacy goes NOWHERE.

Legacy link has been updated recently and can be found [here](https://ractive.js.org/get-started/support/#legacy-versions).

**Comment by hbergren** [comment]
@lnryan - Legacy documentation can be viewed through a localhost http-server by following the instructions on the README at this repo:
https://github.com/ractivejs/v0.x

**Comment by lnryan** [comment]
@fskreuz Just circling back here for a quick shout-out on this...Thank you SO much for getting the legacy docs and 'migrating from' up. super appreciative!

**Comment by clarkd** [comment]
For future readers, the docs are now available at https://ractive.js.org/v0.x/0.8/get-started

**Comment by fskreuz** [comment]
https://ractive.js.org/support/#legacy-documentation now has links to snapshots of select pages prior to a version bump. Currently, it only has API, Plugins, and Concepts since they're pages that most likely change and get compared across versions. The others either get dragged across versions (Support, Resources) or make no sense for older versions (Tutorials).

Will be moving the older docs into this format when I get the time.
