### ISSUE TITLE
Add back the mkdocs search

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractivejs.github.io#67]
Because it's very handy. Beware of the indexing issue though https://github.com/mkdocs/mkdocs/issues/859

**Comment by evs-chris** [comment]
The search is back in a reasonably prominent form, and hopefully the UI is acceptable 😄.

Our index is only 600K at this point, which is actually not too bad considering the volume of content that's indexed. I think the playground attrs are skipped for indexing, which is definitely a good thing. There are some of those that are 4K+. The only thing that's kinda weird is that the links in the search don't have the full context of the heading. They say `Step 1` instead of `Get Started -> Hello, World! -> Step 1`, so some of the results look kinda like dupes.
